package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BidAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBidAllPropertiesEquals(Bid expected, Bid actual) {
        assertBidAutoGeneratedPropertiesEquals(expected, actual);
        assertBidAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBidAllUpdatablePropertiesEquals(Bid expected, Bid actual) {
        assertBidUpdatableFieldsEquals(expected, actual);
        assertBidUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBidAutoGeneratedPropertiesEquals(Bid expected, Bid actual) {
        assertThat(expected)
            .as("Verify Bid auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBidUpdatableFieldsEquals(Bid expected, Bid actual) {
        assertThat(expected)
            .as("Verify Bid relevant properties")
            .satisfies(e -> assertThat(e.getAmount()).as("check amount").isEqualTo(actual.getAmount()))
            .satisfies(e -> assertThat(e.getTimestamp()).as("check timestamp").isEqualTo(actual.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBidUpdatableRelationshipsEquals(Bid expected, Bid actual) {
        assertThat(expected)
            .as("Verify Bid relationships")
            .satisfies(e -> assertThat(e.getAuctionRoom()).as("check auctionRoom").isEqualTo(actual.getAuctionRoom()));
    }
}
