package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LicensePlateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLicensePlateAllPropertiesEquals(LicensePlate expected, LicensePlate actual) {
        assertLicensePlateAutoGeneratedPropertiesEquals(expected, actual);
        assertLicensePlateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLicensePlateAllUpdatablePropertiesEquals(LicensePlate expected, LicensePlate actual) {
        assertLicensePlateUpdatableFieldsEquals(expected, actual);
        assertLicensePlateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLicensePlateAutoGeneratedPropertiesEquals(LicensePlate expected, LicensePlate actual) {
        assertThat(expected)
            .as("Verify LicensePlate auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLicensePlateUpdatableFieldsEquals(LicensePlate expected, LicensePlate actual) {
        assertThat(expected)
            .as("Verify LicensePlate relevant properties")
            .satisfies(e -> assertThat(e.getPlateNumber()).as("check plateNumber").isEqualTo(actual.getPlateNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLicensePlateUpdatableRelationshipsEquals(LicensePlate expected, LicensePlate actual) {
        assertThat(expected)
            .as("Verify LicensePlate relationships")
            .satisfies(e -> assertThat(e.getProvince()).as("check province").isEqualTo(actual.getProvince()))
            .satisfies(e -> assertThat(e.getVehicleType()).as("check vehicleType").isEqualTo(actual.getVehicleType()));
    }
}
